version: 2

updates:
  - package-ecosystem: cargo
    directory: /funcmap
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /funcmap_derive
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /test_suite
    schedule:
      interval: daily
    ignore:
      - dependency-name: quote

  
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily