repository:
  name: funcmap
  description: Derivable functorial mappings for Rust
  topics: data-structures, library, rust

labels:
  - name: "release:pending"
    color: fbca04
    description: Pending release, merge to publish

  - name: "release:published"
    color: 0e8a16
    description: Published release
