[workspace]

[package]
name = "funcmap"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[features]
default = ["alloc", "debug"] # TODO: remove debug
alloc = []
debug = ["funcmap-derive/debug"]

[dependencies]
"funcmap-derive" = { path = "funcmap-derive" }
