[workspace]

[package]
name = "mapstruct"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[features]
default = ["alloc", "debug"] # TODO: remove debug
alloc = []
debug = ["mapstruct-derive/debug"]

[dependencies]
"mapstruct-derive" = { path = "mapstruct-derive" }