[package]
name = "funcmap_derive"
version = "0.1.0"
edition = "2021"
rust-version = "1.56" # should be the same in Cargo.toml of funcmap and in docs
description = "Derivable functorial mappings for Rust"
readme = "README.md"
repository = "https://github.com/matthias-stemmler/funcmap"
license = "MIT OR Apache-2.0"
keywords = ["data", "derive", "macro", "map", "no_std"]
categories = ["algorithms", "data-structures", "development-tools", "no-std", "rust-patterns"]

[lib]
proc-macro = true

[dependencies]
indexmap = { version = "1", features = ["std"] }
proc-macro2 = "1.0.19"
quote = "1"
syn = { version = "1.0.73", features = ["extra-traits", "fold", "visit"] }

[dev-dependencies]
syn = { version = "1.0.73", features = ["full"] }