[package]
name = "funcmap_derive"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[lib]
proc-macro = true

[dependencies]
indexmap = { version = "1", features = ["std"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-traits", "fold", "visit"] }

[dev-dependencies]
rstest = "0.12"
