[package]
name = "test_suite"
version = "0.0.0"
edition = "2021"
rust-version = "1.56"
publish = false

[dev-dependencies]
funcmap = { path = "../funcmap" }
trybuild = "1"

[[test]]
name = "edition2015"
edition = "2015"

[[test]]
name = "edition2018"
edition = "2018"
