[package]
name = "funcmap"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[dependencies]
"funcmap_derive" = { path = "../funcmap_derive" }
