name: Security audit

on:
  push:
    paths:
      - "**/Cargo.toml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  audit:
    name: Cargo audit
    runs-on: ubuntu-latest

    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run audit
        run: cargo audit
