name: Lint commits

on:
  - pull_request
  - workflow_dispatch

jobs:
  committed:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: crate-ci/committed@v1.0.2
