name: Documentation

on: [workflow_call, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  doc:
    name: Cargo doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Run `cargo doc`
        uses: actions-rs/cargo@v1
        with:
          command: doc