name: Minimum supported Rust version

on: [workflow_call, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  msrv:
    name: Cargo check (${{ matrix.toolchain }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [1.56]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - name: Run `cargo check`
        uses: actions-rs/cargo@v1
        with:
          command: check
