name: no-std

on: [workflow_call, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  no-std:
    name: Cargo check (${{ matrix.target }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [thumbv7m-none-eabi, aarch64-unknown-none]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Run `cargo check`
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{ matrix.target }} --no-default-features
