name: Release

on:
  release:
    types: [published]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  publish:
    name: Publish to crates.io
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Publish to crates.io
        run: |
          echo "TODO publish to crates.io"