name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - hotfix/**
  workflow_call:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Cargo test (${{ matrix.toolchain }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]
        exclude:
          - os: macos-latest
            toolchain: nightly

    steps:
      - name: Find tool versions
        id: tool-versions
        if: matrix.toolchain == 'nightly'
        run: |
          echo "::set-output name=cargo-expand::$(curl -s https://crates.io/api/v1/crates/cargo-expand | jq -r .crate.max_version)"

      - name: Cache
        id: cache
        if: matrix.toolchain == 'nightly'
        uses: actions/cache@v2
        with:
          path: ~/.cargo/
          key: cargo-bin-expand-${{ steps.tool-versions.outputs.cargo-expand }}

      - name: Install `cargo-expand`
        if: ${{ matrix.toolchain == 'nightly' && !steps.cache.outputs.cache-hit }}
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-expand
          version: ${{ steps.tool-versions.outputs.cargo-expand }}

      - name: Install latest ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run `cargo test`
        uses: actions-rs/cargo@v1
        with:
          command: test
