name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - hotfix/**
  workflow_call:
  workflow_dispatch:

concurrency: 
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  # renovate: datasource=crate versioning=semver-coerced depName=cargo-expand
  VERSION_CARGO_EXPAND: 1.0.99

jobs:
  test:
    name: Cargo test (${{ matrix.toolchain }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]
        exclude:
          - os: macos-latest
            toolchain: nightly

    steps:
      - name: Cache
        id: cache
        if: matrix.toolchain == 'nightly'
        uses: actions/cache@v4
        with:
          path: ~/.cargo/
          key: cargo-expand-${{ env.VERSION_CARGO_EXPAND }}

      - name: Install `cargo-expand`
        if: ${{ matrix.toolchain == 'nightly' && !steps.cache.outputs.cache-hit }}
        run: cargo install --locked cargo-expand@${{ env.VERSION_CARGO_EXPAND }}

      - name: Install ${{ matrix.toolchain }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: cargo test
