name: Test

on:
  - workflow_call
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Cargo test (${{ matrix.toolchain }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - name: Install `cargo-expand`
        if: matrix.toolchain == 'nightly'
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-expand
          use-tool-cache: true

      - name: Run `cargo test`
        uses: actions-rs/cargo@v1
        with:
          command: test
