name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - hotfix/**
  workflow_call:
  workflow_dispatch:

concurrency: 
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  # renovate: datasource=crate depName=cargo-expand
  VERSION_CARGO_EXPAND: 1.0.54

jobs:
  test:
    name: Cargo test (${{ matrix.toolchain }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]
        exclude:
          - os: macos-latest
            toolchain: nightly

    steps:
      - name: Cache
        id: cache
        if: matrix.toolchain == 'nightly'
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: cargo-expand-${{ env.VERSION_CARGO_EXPAND }}

      - name: Install `cargo-expand`
        if: ${{ matrix.toolchain == 'nightly' && !steps.cache.outputs.cache-hit }}
        run: cargo install --locked cargo-expand@${{ env.VERSION_CARGO_EXPAND }}

      - name: Install latest ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run `cargo test`
        uses: actions-rs/cargo@v1
        with:
          command: test
